name: Python style check

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install nbqa

    - name: Run flake8
      run: nbqa flake8 main.ipynb
      working-directory: myblog
      continue-on-error: false